/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as daoSol from "./DAO.sol";
export type { daoSol };
export type { AITrainer } from "./AITrainer";
export type { YourContract } from "./YourContract";
