/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IAITrainer,
  IAITrainerInterface,
} from "../../../contracts/DAO.sol/IAITrainer";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "proposalId",
        type: "uint256",
      },
      {
        internalType: "string",
        name: "datasetHash",
        type: "string",
      },
    ],
    name: "trainModel",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IAITrainer__factory {
  static readonly abi = _abi;
  static createInterface(): IAITrainerInterface {
    return new Interface(_abi) as IAITrainerInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IAITrainer {
    return new Contract(address, _abi, runner) as unknown as IAITrainer;
  }
}
